CREATE TABLE Element (
    [Id] VARCHAR(255) NOT NULL,
    [Index] INT NOT NULL,
    [ShortName] VARCHAR(255) NOT NULL,
    [ElementName] VARCHAR(255) NOT NULL,
    [AtomicMass] FLOAT NOT NULL,
    [CPKHexColor] VARCHAR(255) NOT NULL,
    [StandardState] VARCHAR(255) NULL,
    [ElectronConfiguration] VARCHAR(255) NULL,
    [OxidationStates] VARCHAR(255) NULL,
    [Electronegativity] FLOAT NULL,
    [AtomicRadius] INT NULL,
    [IonizationEnergy] FLOAT NULL,
    [ElectronAffinity] FLOAT NULL,
    [MeltingPoint] FLOAT NULL,
    [BoilingPoint] FLOAT NULL,
    [Density] FLOAT NULL,
    [GroupBlock] VARCHAR(255) NOT NULL,
    [YearDiscovered] VARCHAR(255) NULL,
    PRIMARY KEY ([Id])
);